//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPN.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSPN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;style&gt;body{text-align:center}#loading{position:fixed;top:50%;left:50%;width:auto;height:150px;-webkit-transform:translateX(-50%) translateY(-50%)}.object{float:left;margin-top:40px;margin-right:30px;width:50px;height:50px;-webkit-border-radius:50% 50% 50% 50%;background-color:#002cff}#object_one{-webkit-animation:object_one 1.5s infinite}#object_two{-webkit-anima [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/script&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body,html{margin:0}#container,body,html{position:absolute;width:100%;height:100%}#container{top:0;right:0;bottom:0;left:0}.search{position:absolute;left:5%;z-index:6201}.searchbox{position:relative;z-index:2201;width:225px;height:40px;border-radius:3px;background:#fff;box-shadow:0 2px 2px rgba(0,0,0,.15)}.searchbox .iptbox{position:absolute;top:0;z-index:2202;box-sizing:border-box;width:225px;height:40px;border-radius:2px}.searchbox #searchipt{position:absolut [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mapContent {
            get {
                return ResourceManager.GetString("mapContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no, width=device-width&quot; /&gt;
        ///    &lt;title&gt;地图&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;http://cache.amap.com/lbs/static/main1119.css&quot; /&gt;
        ///    &lt;script src=&quot;http://webapi.amap.com/maps?v=1.4.3&amp;key=f30294b3e24d47a6986cabdb002d043d&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        var mapdata = eval(&apos;{0}&apos;);
        ///        va [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mapHeader {
            get {
                return ResourceManager.GetString("mapHeader", resourceCulture);
            }
        }
    }
}
